// Collection of REST calls for testing

### Create a new user
POST http://localhost:8080/users
Content-Type: application/json

{ "email" : "test@email.com",
  "firstName": "Test",
  "lastName": "User" }

### Create a listing
POST http://localhost:8080/listings
Content-Type: application/json

{ "title" : "Test Listing",
  "description": "Test Description",
  "price": 100,
  "sellerId": "97a03b64-453f-4c6a-9588-349554eadb15" }

### Get all Listings
GET http://localhost:8080/listings

### Place an Offer
POST http://localhost:8080/offers
Content-Type: application/json

{ "listingId": "e3a77561-5d98-4a6f-9404-02f58f213e01",
  "buyerId": "97a03b64-453f-4c6a-9588-349554eadb15",
  "price": 50 }

### Get Offer
GET http://localhost:8080/offers/a973d332-61ad-4fe5-a2fa-007e14c26641

### Accept an Offer
PUT http://localhost:8080/offers/a973d332-61ad-4fe5-a2fa-007e14c26641/accept

### Reject an Offer
PUT http://localhost:8080/listings/1/offers/1/reject

