server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/xbay-challenge
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    generateDdl: true
    hibernate:
      ddl-auto: update
